# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Card.create(name: "Air Elemental", artist: "Richard Thomas", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_000.jpeg")
Card.create(name: "Ancestral Recall", artist: "Mark Poole", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_001.jpeg")
Card.create(name: "Animate Artifact", artist: "Douglas Schuler", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_002.jpeg")
Card.create(name: "Animate Dead", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_003.jpeg")
Card.create(name: "Animate Wall", artist: "Dan Frazier", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_004.jpeg")
Card.create(name: "Armageddon", artist: "Jesper Myrfors", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_005.jpeg")
Card.create(name: "Aspect of Wolf", artist: "Jeff A. Menges", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_006.jpeg")
Card.create(name: "Bad Moon", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_007.jpeg")
Card.create(name: "Balance", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_008.jpeg")
Card.create(name: "Benalish Hero", artist: "Douglas Schuler", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_009.jpeg")
Card.create(name: "Berserk", artist: "Dan Frazier", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_010.jpeg")
Card.create(name: "Birds of Paradise", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_011.jpeg")
Card.create(name: "Black Knight", artist: "Jeff A. Menges", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_012.jpeg")
Card.create(name: "Black Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_013.jpeg")
Card.create(name: "Blaze of Glory", artist: "Richard Thomas", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_014.jpeg")
Card.create(name: "Blessing", artist: "Julie Baroh", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_015.jpeg")
Card.create(name: "Blue Elemental Blast", artist: "Richard Thomas", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_016.jpeg")
Card.create(name: "Blue Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_017.jpeg")
Card.create(name: "Bog Wraith", artist: "Jeff A. Menges", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_018.jpeg")
Card.create(name: "Braingeyser", artist: "Mark Tedin", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_019.jpeg")
Card.create(name: "Burrowing", artist: "Mark Poole", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_020.jpeg")
Card.create(name: "Camouflage", artist: "Jesper Myrfors", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_021.jpeg")
Card.create(name: "Castle", artist: "Dameon Willich", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_022.jpeg")
Card.create(name: "Channel", artist: "Richard Thomas", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_023.jpeg")
Card.create(name: "Chaoslace", artist: "Dameon Willich", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_024.jpeg")
Card.create(name: "Circle of Protection: Blue", artist: "Dameon Willich", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_025.jpeg")
Card.create(name: "Circle of Protection: Green", artist: "Sandra Everingham", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_026.jpeg")
Card.create(name: "Circle of Protection: Red", artist: "Anson Maddocks", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_027.jpeg")
Card.create(name: "Circle of Protection: White", artist: "Douglas Schuler", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_028.jpeg")
Card.create(name: "Clone", artist: "Julie Baroh", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_029.jpeg")
Card.create(name: "Cockatrice", artist: "Dan Frazier", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_030.jpeg")
Card.create(name: "Consecrate Land", artist: "Jeff A. Menges", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_031.jpeg")
Card.create(name: "Contract from Below", artist: "Douglas Schuler", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_032.jpeg")
Card.create(name: "Control Magic", artist: "Dameon Willich", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_033.jpeg")
Card.create(name: "Conversion", artist: "Jesper Myrfors", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_034.jpeg")
Card.create(name: "Copy Artifact", artist: "Amy Weber", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_035.jpeg")
Card.create(name: "Counterspell", artist: "Mark Poole", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_036.jpeg")
Card.create(name: "Craw Wurm", artist: "Daniel Gelon", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_037.jpeg")
Card.create(name: "Creature Bond", artist: "Anson Maddocks", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_038.jpeg")
Card.create(name: "Crusade", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_039.jpeg")
Card.create(name: "Cursed Land", artist: "Jesper Myrfors", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_040.jpeg")
Card.create(name: "Dark Ritual", artist: "Sandra Everingham", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_041.jpeg")
Card.create(name: "Darkpact", artist: "Quinton Hoover", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_042.jpeg")
Card.create(name: "Death Ward", artist: "Dan Frazier", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_043.jpeg")
Card.create(name: "Deathgrip", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_044.jpeg")
Card.create(name: "Deathlace", artist: "Sandra Everingham", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_045.jpeg")
Card.create(name: "Demonic Attorney", artist: "Daniel Gelon", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_046.jpeg")
Card.create(name: "Demonic Hordes", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_047.jpeg")
Card.create(name: "Demonic Tutor", artist: "Douglas Schuler", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_048.jpeg")
Card.create(name: "Disenchant", artist: "Amy Weber", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_049.jpeg")
Card.create(name: "Disintegrate", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_050.jpeg")
Card.create(name: "Dragon Whelp", artist: "Amy Weber", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_051.jpeg")
Card.create(name: "Drain Life", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_052.jpeg")
Card.create(name: "Drain Power", artist: "Douglas Schuler", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_053.jpeg")
Card.create(name: "Drudge Skeletons", artist: "Sandra Everingham", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_054.jpeg")
Card.create(name: "Dwarven Demolition Team", artist: "Kev Brockschmidt", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_055.jpeg")
Card.create(name: "Dwarven Warriors", artist: "Douglas Schuler", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_056.jpeg")
Card.create(name: "Earth Elemental", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_057.jpeg")
Card.create(name: "Earthbind", artist: "Quinton Hoover", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_058.jpeg")
Card.create(name: "Earthquake", artist: "Dan Frazier", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_059.jpeg")
Card.create(name: "Elvish Archers", artist: "Anson Maddocks", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_060.jpeg")
Card.create(name: "Evil Presence", artist: "Sandra Everingham", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_061.jpeg")
Card.create(name: "False Orders", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_062.jpeg")
Card.create(name: "Farmstead", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_063.jpeg")
Card.create(name: "Fastbond", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_064.jpeg")
Card.create(name: "Fear", artist: "Mark Poole", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_065.jpeg")
Card.create(name: "Feedback", artist: "Quinton Hoover", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_066.jpeg")
Card.create(name: "Fire Elemental", artist: "Melissa Benson", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_067.jpeg")
Card.create(name: "Fireball", artist: "Mark Tedin", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_068.jpeg")
Card.create(name: "Firebreathing", artist: "Dan Frazier", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_069.jpeg")
Card.create(name: "Flashfires", artist: "Dameon Willich", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_070.jpeg")
Card.create(name: "Flight", artist: "Anson Maddocks", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_071.jpeg")
Card.create(name: "Fog", artist: "Jesper Myrfors", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_072.jpeg")
Card.create(name: "Force of Nature", artist: "Douglas Schuler", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_073.jpeg")
Card.create(name: "Fork", artist: "Amy Weber", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_074.jpeg")
Card.create(name: "Frozen Shade", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_075.jpeg")
Card.create(name: "Fungusaur", artist: "Daniel Gelon", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_076.jpeg")
Card.create(name: "Gaea's Liege", artist: "Dameon Willich", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_077.jpeg")
Card.create(name: "Giant Growth", artist: "Sandra Everingham", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_078.jpeg")
Card.create(name: "Giant Spider", artist: "Sandra Everingham", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_079.jpeg")
Card.create(name: "Gloom", artist: "Dan Frazier", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_080.jpeg")
Card.create(name: "Goblin Balloon Brigade", artist: "Andi Rusu", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_081.jpeg")
Card.create(name: "Goblin King", artist: "Jesper Myrfors", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_082.jpeg")
Card.create(name: "Granite Gargoyle", artist: "Christopher Rush", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_083.jpeg")
Card.create(name: "Gray Ogre", artist: "Dan Frazier", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_084.jpeg")
Card.create(name: "Green Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_085.jpeg")
Card.create(name: "Grizzly Bears", artist: "Jeff A. Menges", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_086.jpeg")
Card.create(name: "Guardian Angel", artist: "Anson Maddocks", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_087.jpeg")
Card.create(name: "Healing Salve", artist: "Dan Frazier", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_088.jpeg")
Card.create(name: "Hill Giant", artist: "Dan Frazier", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_089.jpeg")
Card.create(name: "Holy Armor", artist: "Melissa Benson", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_090.jpeg")
Card.create(name: "Holy Strength", artist: "Anson Maddocks", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_091.jpeg")
Card.create(name: "Howl from Beyond", artist: "Mark Poole", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_092.jpeg")
Card.create(name: "Hurloon Minotaur", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_093.jpeg")
Card.create(name: "Hurricane", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_094.jpeg")
Card.create(name: "Hypnotic Specter", artist: "Douglas Schuler", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_095.jpeg")
Card.create(name: "Ice Storm", artist: "Dan Frazier", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_096.jpeg")
Card.create(name: "Instill Energy", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_097.jpeg")
Card.create(name: "Invisibility", artist: "Anson Maddocks", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_098.jpeg")
Card.create(name: "Ironclaw Orcs", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_099.jpeg")
Card.create(name: "Ironroot Treefolk", artist: "Jesper Myrfors", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_100.jpeg")
Card.create(name: "Island Sanctuary", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_101.jpeg")
Card.create(name: "Jump", artist: "Mark Poole", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_102.jpeg")
Card.create(name: "Karma", artist: "Richard Thomas", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_103.jpeg")
Card.create(name: "Keldon Warlord", artist: "Kev Brockschmidt", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_104.jpeg")
Card.create(name: "Kudzu", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_105.jpeg")
Card.create(name: "Lance", artist: "Rob Alexander", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_106.jpeg")
Card.create(name: "Ley Druid", artist: "Sandra Everingham", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_107.jpeg")
Card.create(name: "Lich", artist: "Daniel Gelon", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_108.jpeg")
Card.create(name: "Lifeforce", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_109.jpeg")
Card.create(name: "Lifelace", artist: "Amy Weber", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_110.jpeg")
Card.create(name: "Lifetap", artist: "Anson Maddocks", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_111.jpeg")
Card.create(name: "Lightning Bolt", artist: "Christopher Rush", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_112.jpeg")
Card.create(name: "Living Artifact", artist: "Anson Maddocks", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_113.jpeg")
Card.create(name: "Living Lands", artist: "Jesper Myrfors", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_114.jpeg")
Card.create(name: "Llanowar Elves", artist: "Anson Maddocks", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_115.jpeg")
Card.create(name: "Lord of Atlantis", artist: "Melissa Benson", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_116.jpeg")
Card.create(name: "Lord of the Pit", artist: "Mark Tedin", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_117.jpeg")
Card.create(name: "Lure", artist: "Anson Maddocks", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_118.jpeg")
Card.create(name: "Magical Hack", artist: "Julie Baroh", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_119.jpeg")
Card.create(name: "Mahamoti Djinn", artist: "Dan Frazier", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_120.jpeg")
Card.create(name: "Mana Flare", artist: "Christopher Rush", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_121.jpeg")
Card.create(name: "Mana Short", artist: "Dameon Willich", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_122.jpeg")
Card.create(name: "Manabarbs", artist: "Christopher Rush", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_123.jpeg")
Card.create(name: "Merfolk of the Pearl Trident", artist: "Jeff A. Menges", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_124.jpeg")
Card.create(name: "Mesa Pegasus", artist: "Melissa Benson", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_125.jpeg")
Card.create(name: "Mind Twist", artist: "Julie Baroh", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_126.jpeg")
Card.create(name: "Mons's Goblin Raiders", artist: "Jeff A. Menges", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_127.jpeg")
Card.create(name: "Natural Selection", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_128.jpeg")
Card.create(name: "Nether Shadow", artist: "Christopher Rush", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_129.jpeg")
Card.create(name: "Nettling Imp", artist: "Quinton Hoover", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_130.jpeg")
Card.create(name: "Nightmare", artist: "Melissa Benson", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_131.jpeg")
Card.create(name: "Northern Paladin", artist: "Douglas Schuler", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_132.jpeg")
Card.create(name: "Orcish Artillery", artist: "Anson Maddocks", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_133.jpeg")
Card.create(name: "Orcish Oriflamme", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_134.jpeg")
Card.create(name: "Paralyze", artist: "Anson Maddocks", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_135.jpeg")
Card.create(name: "Pearled Unicorn", artist: "Cornelius Brudi", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_136.jpeg")
Card.create(name: "Personal Incarnation", artist: "Kev Brockschmidt", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_137.jpeg")
Card.create(name: "Pestilence", artist: "Jesper Myrfors", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_138.jpeg")
Card.create(name: "Phantasmal Forces", artist: "Mark Poole", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_139.jpeg")
Card.create(name: "Phantasmal Terrain", artist: "Dameon Willich", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_140.jpeg")
Card.create(name: "Phantom Monster", artist: "Jesper Myrfors", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_141.jpeg")
Card.create(name: "Pirate Ship", artist: "Tom Wänerstrand", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_142.jpeg")
Card.create(name: "Plague Rats", artist: "Anson Maddocks", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_143.jpeg")
Card.create(name: "Power Leak", artist: "Drew Tucker", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_144.jpeg")
Card.create(name: "Power Sink", artist: "Richard Thomas", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_145.jpeg")
Card.create(name: "Power Surge", artist: "Douglas Schuler", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_146.jpeg")
Card.create(name: "Prodigal Sorcerer", artist: "Douglas Schuler", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_147.jpeg")
Card.create(name: "Psionic Blast", artist: "Douglas Schuler", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_148.jpeg")
Card.create(name: "Psychic Venom", artist: "Brian Snoddy", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_149.jpeg")
Card.create(name: "Purelace", artist: "Sandra Everingham", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_150.jpeg")
Card.create(name: "Raging River", artist: "Sandra Everingham", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_151.jpeg")
Card.create(name: "Raise Dead", artist: "Jeff A. Menges", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_152.jpeg")
Card.create(name: "Red Elemental Blast", artist: "Richard Thomas", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_153.jpeg")
Card.create(name: "Red Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_154.jpeg")
Card.create(name: "Regeneration", artist: "Quinton Hoover", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_155.jpeg")
Card.create(name: "Regrowth", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_156.jpeg")
Card.create(name: "Resurrection", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_157.jpeg")
Card.create(name: "Reverse Damage", artist: "Dameon Willich", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_158.jpeg")
Card.create(name: "Righteousness", artist: "Douglas Schuler", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_159.jpeg")
Card.create(name: "Roc of Kher Ridges", artist: "Andi Rusu", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_160.jpeg")
Card.create(name: "Rock Hydra", artist: "Jeff A. Menges", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_161.jpeg")
Card.create(name: "Royal Assassin", artist: "Tom Wänerstrand", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_162.jpeg")
Card.create(name: "Sacrifice", artist: "Dan Frazier", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_163.jpeg")
Card.create(name: "Samite Healer", artist: "Tom Wänerstrand", color: "White", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_164.jpeg")
Card.create(name: "Savannah Lions", artist: "Daniel Gelon", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_165.jpeg")
Card.create(name: "Scathe Zombies", artist: "Jesper Myrfors", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_166.jpeg")
Card.create(name: "Scavenging Ghoul", artist: "Jeff A. Menges", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_167.jpeg")
Card.create(name: "Scryb Sprites", artist: "Amy Weber", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_168.jpeg")
Card.create(name: "Sea Serpent", artist: "Jeff A. Menges", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_169.jpeg")
Card.create(name: "Sedge Troll", artist: "Jeff A. Menges", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_170.jpeg")
Card.create(name: "Sengir Vampire", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_171.jpeg")
Card.create(name: "Serra Angel", artist: "Douglas Schuler", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_172.jpeg")
Card.create(name: "Shanodin Dryads", artist: "Anson Maddocks", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_173.jpeg")
Card.create(name: "Shatter", artist: "Amy Weber", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_174.jpeg")
Card.create(name: "Shivan Dragon", artist: "Melissa Benson", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_175.jpeg")
Card.create(name: "Simulacrum", artist: "Mark Poole", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_176.jpeg")
Card.create(name: "Sinkhole", artist: "Sandra Everingham", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_177.jpeg")
Card.create(name: "Siren's Call", artist: "Anson Maddocks", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_178.jpeg")
Card.create(name: "Sleight of Mind", artist: "Mark Poole", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_179.jpeg")
Card.create(name: "Smoke", artist: "Jesper Myrfors", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_180.jpeg")
Card.create(name: "Spell Blast", artist: "Brian Snoddy", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_181.jpeg")
Card.create(name: "Stasis", artist: "Fay Jones", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_182.jpeg")
Card.create(name: "Steal Artifact", artist: "Amy Weber", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_183.jpeg")
Card.create(name: "Stone Giant", artist: "Dameon Willich", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_184.jpeg")
Card.create(name: "Stone Rain", artist: "Daniel Gelon", color: "Red", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_185.jpeg")
Card.create(name: "Stream of Life", artist: "Mark Poole", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_186.jpeg")
Card.create(name: "Swords to Plowshares", artist: "Jeff A. Menges", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_187.jpeg")
Card.create(name: "Terror", artist: "Ron Spencer", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_188.jpeg")
Card.create(name: "Thicket Basilisk", artist: "Dan Frazier", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_189.jpeg")
Card.create(name: "Thoughtlace", artist: "Mark Poole", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_190.jpeg")
Card.create(name: "Timber Wolves", artist: "Melissa Benson", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_191.jpeg")
Card.create(name: "Time Walk", artist: "Amy Weber", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_192.jpeg")
Card.create(name: "Timetwister", artist: "Mark Tedin", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_193.jpeg")
Card.create(name: "Tranquility", artist: "Douglas Schuler", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_194.jpeg")
Card.create(name: "Tsunami", artist: "Richard Thomas", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_195.jpeg")
Card.create(name: "Tunnel", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_196.jpeg")
Card.create(name: "Twiddle", artist: "Rob Alexander", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_197.jpeg")
Card.create(name: "Two-Headed Giant of Foriys", artist: "Anson Maddocks", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_198.jpeg")
Card.create(name: "Unholy Strength", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_199.jpeg")
Card.create(name: "Unsummon", artist: "Douglas Schuler", color: "Blue", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_200.jpeg")
Card.create(name: "Uthden Troll", artist: "Douglas Schuler", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_201.jpeg")
Card.create(name: "Verduran Enchantress", artist: "Kev Brockschmidt", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_202.jpeg")
Card.create(name: "Vesuvan Doppelganger", artist: "Quinton Hoover", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_203.jpeg")
Card.create(name: "Veteran Bodyguard", artist: "Douglas Schuler", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_204.jpeg")
Card.create(name: "Volcanic Eruption", artist: "Douglas Schuler", color: "Blue", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_205.jpeg")
Card.create(name: "Wall of Air", artist: "Richard Thomas", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_206.jpeg")
Card.create(name: "Wall of Bone", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_207.jpeg")
Card.create(name: "Wall of Brambles", artist: "Anson Maddocks", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_208.jpeg")
Card.create(name: "Wall of Fire", artist: "Richard Thomas", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_209.jpeg")
Card.create(name: "Wall of Ice", artist: "Richard Thomas", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_210.jpeg")
Card.create(name: "Wall of Stone", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_211.jpeg")
Card.create(name: "Wall of Swords", artist: "Mark Tedin", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_212.jpeg")
Card.create(name: "Wall of Water", artist: "Richard Thomas", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_213.jpeg")
Card.create(name: "Wall of Wood", artist: "Mark Tedin", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_214.jpeg")
Card.create(name: "Wanderlust", artist: "Cornelius Brudi", color: "Green", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_215.jpeg")
Card.create(name: "War Mammoth", artist: "Jeff A. Menges", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_216.jpeg")
Card.create(name: "Warp Artifact", artist: "Amy Weber", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_217.jpeg")
Card.create(name: "Water Elemental", artist: "Jeff A. Menges", color: "Blue", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_218.jpeg")
Card.create(name: "Weakness", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_219.jpeg")
Card.create(name: "Web", artist: "Rob Alexander", color: "Green", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_220.jpeg")
Card.create(name: "Wheel of Fortune", artist: "Daniel Gelon", color: "Red", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_221.jpeg")
Card.create(name: "White Knight", artist: "Daniel Gelon", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_222.jpeg")
Card.create(name: "White Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha", imgsrc: "cards/image_223.jpeg")
Card.create(name: "Wild Growth", artist: "Mark Poole", color: "Green", rarity: 1, set: "Limited Edition Alpha", imgsrc: "cards/image_224.jpeg")
Card.create(name: "Will-o'-the-Wisp", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_225.jpeg")
Card.create(name: "Word of Command", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_226.jpeg")
Card.create(name: "Wrath of God", artist: "Quinton Hoover", color: "White", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_227.jpeg")
Card.create(name: "Zombie Master", artist: "Jeff A. Menges", color: "Black", rarity: 3, set: "Limited Edition Alpha", imgsrc: "cards/image_228.jpeg")