# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Card.create(name: "Air Elemental", artist: "Richard Thomas", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Ancestral Recall", artist: "Mark Poole", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Animate Artifact", artist: "Douglas Schuler", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Animate Dead", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Animate Wall", artist: "Dan Frazier", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Armageddon", artist: "Jesper Myrfors", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Aspect of Wolf", artist: "Jeff A. Menges", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Bad Moon", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Balance", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Benalish Hero", artist: "Douglas Schuler", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Berserk", artist: "Dan Frazier", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Birds of Paradise", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Black Knight", artist: "Jeff A. Menges", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Black Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Blaze of Glory", artist: "Richard Thomas", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Blessing", artist: "Julie Baroh", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Blue Elemental Blast", artist: "Richard Thomas", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Blue Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Bog Wraith", artist: "Jeff A. Menges", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Braingeyser", artist: "Mark Tedin", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Burrowing", artist: "Mark Poole", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Camouflage", artist: "Jesper Myrfors", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Castle", artist: "Dameon Willich", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Channel", artist: "Richard Thomas", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Chaoslace", artist: "Dameon Willich", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Circle of Protection: Blue", artist: "Dameon Willich", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Circle of Protection: Green", artist: "Sandra Everingham", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Circle of Protection: Red", artist: "Anson Maddocks", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Circle of Protection: White", artist: "Douglas Schuler", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Clone", artist: "Julie Baroh", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Cockatrice", artist: "Dan Frazier", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Consecrate Land", artist: "Jeff A. Menges", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Contract from Below", artist: "Douglas Schuler", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Control Magic", artist: "Dameon Willich", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Conversion", artist: "Jesper Myrfors", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Copy Artifact", artist: "Amy Weber", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Counterspell", artist: "Mark Poole", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Craw Wurm", artist: "Daniel Gelon", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Creature Bond", artist: "Anson Maddocks", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Crusade", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Cursed Land", artist: "Jesper Myrfors", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Dark Ritual", artist: "Sandra Everingham", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Darkpact", artist: "Quinton Hoover", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Death Ward", artist: "Dan Frazier", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Deathgrip", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Deathlace", artist: "Sandra Everingham", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Demonic Attorney", artist: "Daniel Gelon", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Demonic Hordes", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Demonic Tutor", artist: "Douglas Schuler", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Disenchant", artist: "Amy Weber", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Disintegrate", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Dragon Whelp", artist: "Amy Weber", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Drain Life", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Drain Power", artist: "Douglas Schuler", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Drudge Skeletons", artist: "Sandra Everingham", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Dwarven Demolition Team", artist: "Kev Brockschmidt", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Dwarven Warriors", artist: "Douglas Schuler", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Earth Elemental", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Earthbind", artist: "Quinton Hoover", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Earthquake", artist: "Dan Frazier", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Elvish Archers", artist: "Anson Maddocks", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Evil Presence", artist: "Sandra Everingham", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "False Orders", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Farmstead", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Fastbond", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Fear", artist: "Mark Poole", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Feedback", artist: "Quinton Hoover", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Fire Elemental", artist: "Melissa Benson", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Fireball", artist: "Mark Tedin", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Firebreathing", artist: "Dan Frazier", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Flashfires", artist: "Dameon Willich", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Flight", artist: "Anson Maddocks", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Fog", artist: "Jesper Myrfors", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Force of Nature", artist: "Douglas Schuler", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Fork", artist: "Amy Weber", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Frozen Shade", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Fungusaur", artist: "Daniel Gelon", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Gaea's Liege", artist: "Dameon Willich", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Giant Growth", artist: "Sandra Everingham", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Giant Spider", artist: "Sandra Everingham", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Gloom", artist: "Dan Frazier", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Goblin Balloon Brigade", artist: "Andi Rusu", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Goblin King", artist: "Jesper Myrfors", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Granite Gargoyle", artist: "Christopher Rush", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Gray Ogre", artist: "Dan Frazier", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Green Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Grizzly Bears", artist: "Jeff A. Menges", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Guardian Angel", artist: "Anson Maddocks", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Healing Salve", artist: "Dan Frazier", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Hill Giant", artist: "Dan Frazier", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Holy Armor", artist: "Melissa Benson", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Holy Strength", artist: "Anson Maddocks", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Howl from Beyond", artist: "Mark Poole", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Hurloon Minotaur", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Hurricane", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Hypnotic Specter", artist: "Douglas Schuler", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Ice Storm", artist: "Dan Frazier", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Instill Energy", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Invisibility", artist: "Anson Maddocks", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Ironclaw Orcs", artist: "Anson Maddocks", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Ironroot Treefolk", artist: "Jesper Myrfors", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Island Sanctuary", artist: "Mark Poole", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Jump", artist: "Mark Poole", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Karma", artist: "Richard Thomas", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Keldon Warlord", artist: "Kev Brockschmidt", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Kudzu", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Lance", artist: "Rob Alexander", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Ley Druid", artist: "Sandra Everingham", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Lich", artist: "Daniel Gelon", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Lifeforce", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Lifelace", artist: "Amy Weber", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Lifetap", artist: "Anson Maddocks", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Lightning Bolt", artist: "Christopher Rush", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Living Artifact", artist: "Anson Maddocks", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Living Lands", artist: "Jesper Myrfors", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Llanowar Elves", artist: "Anson Maddocks", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Lord of Atlantis", artist: "Melissa Benson", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Lord of the Pit", artist: "Mark Tedin", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Lure", artist: "Anson Maddocks", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Magical Hack", artist: "Julie Baroh", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Mahamoti Djinn", artist: "Dan Frazier", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Mana Flare", artist: "Christopher Rush", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Mana Short", artist: "Dameon Willich", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Manabarbs", artist: "Christopher Rush", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Merfolk of the Pearl Trident", artist: "Jeff A. Menges", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Mesa Pegasus", artist: "Melissa Benson", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Mind Twist", artist: "Julie Baroh", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Mons's Goblin Raiders", artist: "Jeff A. Menges", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Natural Selection", artist: "Mark Poole", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Nether Shadow", artist: "Christopher Rush", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Nettling Imp", artist: "Quinton Hoover", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Nightmare", artist: "Melissa Benson", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Northern Paladin", artist: "Douglas Schuler", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Orcish Artillery", artist: "Anson Maddocks", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Orcish Oriflamme", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Paralyze", artist: "Anson Maddocks", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Pearled Unicorn", artist: "Cornelius Brudi", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Personal Incarnation", artist: "Kev Brockschmidt", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Pestilence", artist: "Jesper Myrfors", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Phantasmal Forces", artist: "Mark Poole", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Phantasmal Terrain", artist: "Dameon Willich", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Phantom Monster", artist: "Jesper Myrfors", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Pirate Ship", artist: "Tom Wänerstrand", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Plague Rats", artist: "Anson Maddocks", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Power Leak", artist: "Drew Tucker", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Power Sink", artist: "Richard Thomas", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Power Surge", artist: "Douglas Schuler", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Prodigal Sorcerer", artist: "Douglas Schuler", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Psionic Blast", artist: "Douglas Schuler", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Psychic Venom", artist: "Brian Snoddy", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Purelace", artist: "Sandra Everingham", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Raging River", artist: "Sandra Everingham", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Raise Dead", artist: "Jeff A. Menges", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Red Elemental Blast", artist: "Richard Thomas", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Red Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Regeneration", artist: "Quinton Hoover", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Regrowth", artist: "Dameon Willich", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Resurrection", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Reverse Damage", artist: "Dameon Willich", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Righteousness", artist: "Douglas Schuler", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Roc of Kher Ridges", artist: "Andi Rusu", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Rock Hydra", artist: "Jeff A. Menges", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Royal Assassin", artist: "Tom Wänerstrand", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Sacrifice", artist: "Dan Frazier", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Samite Healer", artist: "Tom Wänerstrand", color: "White", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Savannah Lions", artist: "Daniel Gelon", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Scathe Zombies", artist: "Jesper Myrfors", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Scavenging Ghoul", artist: "Jeff A. Menges", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Scryb Sprites", artist: "Amy Weber", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Sea Serpent", artist: "Jeff A. Menges", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Sedge Troll", artist: "Jeff A. Menges", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Sengir Vampire", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Serra Angel", artist: "Douglas Schuler", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Shanodin Dryads", artist: "Anson Maddocks", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Shatter", artist: "Amy Weber", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Shivan Dragon", artist: "Melissa Benson", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Simulacrum", artist: "Mark Poole", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Sinkhole", artist: "Sandra Everingham", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Siren's Call", artist: "Anson Maddocks", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Sleight of Mind", artist: "Mark Poole", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Smoke", artist: "Jesper Myrfors", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Spell Blast", artist: "Brian Snoddy", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Stasis", artist: "Fay Jones", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Steal Artifact", artist: "Amy Weber", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Stone Giant", artist: "Dameon Willich", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Stone Rain", artist: "Daniel Gelon", color: "Red", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Stream of Life", artist: "Mark Poole", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Swords to Plowshares", artist: "Jeff A. Menges", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Terror", artist: "Ron Spencer", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Thicket Basilisk", artist: "Dan Frazier", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Thoughtlace", artist: "Mark Poole", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Timber Wolves", artist: "Melissa Benson", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Time Walk", artist: "Amy Weber", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Timetwister", artist: "Mark Tedin", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Tranquility", artist: "Douglas Schuler", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Tsunami", artist: "Richard Thomas", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Tunnel", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Twiddle", artist: "Rob Alexander", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Two-Headed Giant of Foriys", artist: "Anson Maddocks", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Unholy Strength", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Unsummon", artist: "Douglas Schuler", color: "Blue", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Uthden Troll", artist: "Douglas Schuler", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Verduran Enchantress", artist: "Kev Brockschmidt", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Vesuvan Doppelganger", artist: "Quinton Hoover", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Veteran Bodyguard", artist: "Douglas Schuler", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Volcanic Eruption", artist: "Douglas Schuler", color: "Blue", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Wall of Air", artist: "Richard Thomas", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Bone", artist: "Anson Maddocks", color: "Black", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Brambles", artist: "Anson Maddocks", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Fire", artist: "Richard Thomas", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Ice", artist: "Richard Thomas", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Stone", artist: "Dan Frazier", color: "Red", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Swords", artist: "Mark Tedin", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Water", artist: "Richard Thomas", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wall of Wood", artist: "Mark Tedin", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Wanderlust", artist: "Cornelius Brudi", color: "Green", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "War Mammoth", artist: "Jeff A. Menges", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Warp Artifact", artist: "Amy Weber", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Water Elemental", artist: "Jeff A. Menges", color: "Blue", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Weakness", artist: "Douglas Schuler", color: "Black", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Web", artist: "Rob Alexander", color: "Green", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Wheel of Fortune", artist: "Daniel Gelon", color: "Red", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "White Knight", artist: "Daniel Gelon", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "White Ward", artist: "Dan Frazier", color: "White", rarity: 2, set: "Limited Edition Alpha")
Card.create(name: "Wild Growth", artist: "Mark Poole", color: "Green", rarity: 1, set: "Limited Edition Alpha")
Card.create(name: "Will-o'-the-Wisp", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Word of Command", artist: "Jesper Myrfors", color: "Black", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Wrath of God", artist: "Quinton Hoover", color: "White", rarity: 3, set: "Limited Edition Alpha")
Card.create(name: "Zombie Master", artist: "Jeff A. Menges", color: "Black", rarity: 3, set: "Limited Edition Alpha")